#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail # -o xtrace

cleanup() {
    if [ ${exit_code} -ne 0 ]; then
        case ${commit_point} in
        3)
            rm --force "${bin_dir}/cloud-clipboard"
            ;&
        2)
            rm --force --recursive "${venv_dir}/${project}"
            ;&
        1)
            rm --force --recursive "${src_dir}/${project}"
            ;;
        esac
    fi
}

trap 'exit_code=$?; set +o errexit +o xtrace; cleanup > /dev/null 2>&1; exit ${exit_code}' EXIT
commit_point=0

prefix=${PREFIX:-/usr/local}
dir=$(dirname $(realpath $0))

project=cloud-clipboard
src_dir=${prefix}/src; mkdir --parents "${src_dir}"
venv_dir=${prefix}/venv; mkdir --parents "${venv_dir}"
bin_dir=${prefix}/bin; mkdir --parents "${bin_dir}"

cp --no-target-directory --force --recursive "${dir}" "${src_dir}/${project}"
commit_point=1

virtualenv --python python3 "${venv_dir}/${project}"
commit_point=2

"${venv_dir}/${project}/bin/pip" install --requirement "${dir}/requirements.txt"

tee > "${bin_dir}/cloud-clipboard" << EOF
#!/bin/sh
exec '${venv_dir}/${project}/bin/python' '${src_dir}/${project}/cloud_clipboard.py' "\$@"
EOF
commit_point=3

chmod +x "${bin_dir}/cloud-clipboard"
